-- -------------------------
-- Drop indexes (explicit / partial first)
-- -------------------------

DROP INDEX IF EXISTS "idx_api_keys_customer_id_created_at_desc_active";
DROP INDEX IF EXISTS "idx_optimization_runs_active";
DROP INDEX IF EXISTS "idx_providers_active";
DROP INDEX IF EXISTS "idx_constraints_active";

DROP INDEX IF EXISTS "idx_provider_features_provider_id";
DROP INDEX IF EXISTS "idx_provider_constraints_provider_id";
DROP INDEX IF EXISTS "idx_provider_access_methods_provider_id";

DROP INDEX IF EXISTS "idx_optimization_vehicle_vehicle_id";
DROP INDEX IF EXISTS "idx_optimization_vehicle_optimization_id";

DROP INDEX IF EXISTS "idx_optimization_id";
DROP INDEX IF EXISTS "idx_optimization_runs_provider_id";
DROP INDEX IF EXISTS "idx_optimization_runs_optimization_id";
DROP INDEX IF EXISTS "idx_optimizations_customer_id";

DROP INDEX IF EXISTS "idx_vehicles_plate";
DROP INDEX IF EXISTS "idx_vehicles_customer_id";

DROP INDEX IF EXISTS "idx_constraints_customer_id";
DROP INDEX IF EXISTS "idx_api_keys_customer_id";

-- Anonymous unique indexes (generated by CREATE UNIQUE INDEX)
DROP INDEX IF EXISTS "idx_unique_constraints_customer_id_kind";
DROP INDEX IF EXISTS "idx_unique_vehicles_customer_id_plate";
DROP INDEX IF EXISTS "idx_unique_optimization_waypoints_optimization_id_sequence";

-- -------------------------
-- Drop tables (children → parents)
-- -------------------------

DROP TABLE IF EXISTS "provider_features";
DROP TABLE IF EXISTS "provider_constraints";
DROP TABLE IF EXISTS "provider_access_methods";

DROP TABLE IF EXISTS "optimization_vehicles";
DROP TABLE IF EXISTS "optimization_waypoints";
DROP TABLE IF EXISTS "optimization_runs";
DROP TABLE IF EXISTS "optimizations";

DROP TABLE IF EXISTS "vehicles";
DROP TABLE IF EXISTS "constraints";
DROP TABLE IF EXISTS "api_keys";
DROP TABLE IF EXISTS "providers";
DROP TABLE IF EXISTS "customers";

-- -------------------------
-- Drop enums
-- -------------------------

DROP TYPE IF EXISTS "cargo_kind";
DROP TYPE IF EXISTS "request_kind";
DROP TYPE IF EXISTS "communication_method";
DROP TYPE IF EXISTS "optimization_status";
DROP TYPE IF EXISTS "constraint_kind";

-- -------------------------
-- Drop extension
-- -------------------------

DROP EXTENSION IF EXISTS "uuid-ossp";
